apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-mpa-app
  labels:
    app: react-mpa-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-mpa-app
  template:
    metadata:
      labels:
        app: react-mpa-app
    spec:
      containers:
        - name: react-mpa-container
          image: $DEPLOY_IMAGE
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: react-mpa-service
spec:
  type: NodePort
  selector:
    app: react-mpa-app
  ports:
    - port: 8080
      targetPort: 3000
      nodePort: 30080
