---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: cicd
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://admin:admin@cluster0.la6jq.mongodb.net/formdata?retryWrites=true&w=majority&appName=Cluster0"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-mpa-app
  namespace: cicd
  labels:
    app: react-mpa-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-mpa-app
  template:
    metadata:
      labels:
        app: react-mpa-app
    spec:
      containers:
        - name: react-mpa-container
          image: $DEPLOY_IMAGE
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_URI
---
apiVersion: v1
kind: Service
metadata:
  name: react-mpa-service
  namespace: cicd
spec:
  type: NodePort
  selector:
    app: react-mpa-app
  ports:
    - port: 8080
      targetPort: 3000
      nodePort: 30080
---
